#Python 3.8.5
#cuda_11.0
#gcc (GCC) 6.3.0


absl-py==0.10.0
access==1.1.3
addict==2.4.0
affine==2.3.0
aiohttp==3.7.3
aiohttp-cors==0.7.0
aioredis==1.3.1
alabaster==0.7.12
alembic==1.7.7
amply==0.1.4
aniso8601==9.0.1
anndata==0.7.4
antlr4-python3-runtime==4.9.3
anyio==2.2.0
apex==0.1
appdirs==1.4.4
apptools==5.1.0
APScheduler==3.9.1
argh==0.26.2
argon2-cffi==20.1.0
arviz==0.11.2
ase==3.20.1
asn1crypto==1.4.0
astor==0.8.1
astroid==2.5.6
astunparse==1.6.3
async-generator==1.10
async-timeout==3.0.1
atomicwrites==1.4.0
attmap==0.13.2
attrs==23.1.0
audioread==2.1.9
autopep8==1.5.6
av==9.2.0
Babel==2.8.0
backcall==0.2.0
backports.zoneinfo==0.2.1
bash_kernel==0.7.2
beautifulsoup4==4.11.1
bidict==0.21.2
bids-validator==1.5.4
biopython==1.76
bitstring==3.1.7
bleach==3.2.1
blessings==1.7
blinker==1.4
bokeh==2.2.1
Bottleneck==1.3.2
cachetools==4.2.2
calliope==0.6.6.post1
Cartopy==0.19.0.post1
cattrs==23.1.2
certifi==2024.2.2
certipy==0.1.3
cffi==1.14.3
cfgrib==0.9.9.0
cfgv==3.3.1
cftime==1.2.1
chardet==3.0.4
charset-normalizer==3.3.2
click==8.1.7
click-plugins==1.1.1
cligj==0.7.1
climada @ https://github.com/CLIMADA-project/climada_python/archive/refs/tags/v2.1.1.tar.gz
cloudpickle==1.6.0
cmake==3.26.0
CNVkit==0.9.8
codecov==2.1.11
colorama==0.4.4
coloredlogs==15.0.1
colorful==0.5.4
colorlog==4.7.2
colorlover==0.3.0
colormath==3.0.0
commonmark==0.9.1
ConfigArgParse==1.2.3
configobj==5.0.6
configparser==5.0.2
contextily==1.1.0
coverage==5.5
cryptography==39.0.2
cufflinks==0.17.3
cupy-cuda110==9.5.0
cutadapt==3.5
cvxopt==1.2.6
cvxpy==1.1.13
cycler==0.10.0
cykhash==1.0.2
Cython==0.29.21
dask==2021.1.1
datrie==0.8.2
deap==1.3.1
dearpygui==1.4.0
decorator==4.4.2
deepdiff==5.0.2
deepTools==3.5.1
deeptoolsintervals==0.1.9
deeptrack==1.4.1
defusedxml==0.6.0
DendroPy==4.5.2
Deprecated==1.2.10
deprecation==2.1.0
descartes==1.1.0
diffusers==0.12.1
dill==0.3.3
distlib==0.3.6
distributed==2021.1.1
dm-tree==0.1.5
dnaio==0.6.0
dnspython==2.2.1
docker-pycreds==0.4.0
docopt==0.6.2
docstring-parser==0.14.1
docutils==0.16
easydict==1.9
eccodes==1.3.2
ecos==2.0.7.post1
eggnog-mapper==2.1.6
email-validator==1.2.0
entrypoints==0.4
envisage==5.0.0
eofs==1.4.0
ephem==3.7.7.1
esda==2.3.6
et-xmlfile==1.0.1
ete==1.0.0
ete3==3.1.2
exceptiongroup==1.1.2
fastalite==0.3
fastprogress==1.0.0
fastrlock==0.6
filelock==3.8.2
files2rouge==2.1.0
findlibs==0.0.1
Fiona==1.8.19
flapison==0.30.10
Flask==2.0.3
Flask-APScheduler==1.12.3
Flask-Caching==1.10.1
Flask-DebugToolbar==0.13.1
Flask-Login==0.6.0
flask-marshmallow==0.14.0
Flask-Migrate==3.1.0
Flask-RESTful==0.3.9
flask-restplus==0.13.0
flask-restx==0.3.0
Flask-SocketIO==5.0.1
Flask-SQLAlchemy==2.5.1
Flask-Uploads==0.2.1
Flask-WTF==1.0.1
flatbuffers==1.12
flatten-json==0.1.13
flit==3.0.0
flit_core==3.0.0
freetype-py==2.4.0
frozendict==2.4.4
fsspec==2023.3.0
funcsigs==1.0.2
future==0.18.2
gast==0.3.3
GDAL==3.1.2
gdown==4.5.1
geographiclib==1.50
geopandas==0.9.0
geopy==2.1.0
gevent==21.1.2
giddy==2.3.3
gin-config==0.5.0
gitdb==4.0.5
gitdb2==4.0.2
GitPython==3.1.9
google-api-core==1.25.0
google-auth==2.17.3
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
googleapis-common-protos==1.52.0
googledrivedownloader==0.4
gprMax==3.1.5
gpustat==0.6.0
GPUtil==1.4.0
grabbit==0.2.6
graphtools==1.5.2
greenlet==1.0.0
grpcio==1.54.0
gurobipy==9.1.1
h5py==3.7.0
haversine==2.3.0
HeapDict==1.0.1
hiredis==1.1.0
html5lib==1.1
huggingface-hub==0.16.4
humanfriendly==10.0
hyperopt==0.2.4
identify==2.5.11
idna==3.7
imageio==2.21.1
imageio-ffmpeg==0.4.4
imagesize==1.2.0
imbalanced-learn==0.7.0
importlib-resources==5.1.2
importlib_metadata==7.1.0
inequality==1.0.0
iniconfig==1.1.1
inplace-abn==1.1.0
install==1.3.4
ipdb==0.13.7
ipykernel==5.3.4
ipython==7.34.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
isal==0.11.1
iso3166==1.0.1
isodate==0.6.0
isort==5.8.0
iteration-utilities==0.11.0
itsdangerous==2.1.2
jedi==0.17.2
jeepney==0.6.0
Jinja2==3.1.2
joblib==0.17.0
jobstats==1.2.5
json5==0.9.5
jsonpickle==1.4.1
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.7
jupyter-console==6.2.0
jupyter-contrib-core==0.3.3
jupyter-core==4.6.3
jupyter-highlight-selected-word==0.2.0
jupyter-nbextensions-configurator==0.4.1
jupyter-openbis-server==0.4.2
jupyter-packaging==0.10.4
jupyter-resource-usage==0.6.1
jupyter-server==1.6.0
jupyter-telemetry==0.1.0
jupyter_server_proxy==4.0.0
jupyterhub==3.0.0
jupyterlab==3.0.16
jupyterlab-openbis==0.3.0
jupyterlab-pygments==0.1.2
jupyterlab-server==2.4.0
jupyterlab-widgets==1.0.0
kaolin==0.13.0
Keras==2.4.3
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
keyring==23.0.1
kiwisolver==1.2.0
kornia==0.6.8
lapsolver==1.1.0
lazy-object-proxy==1.6.0
libpysal==4.4.0
librosa==0.8.0
lit==16.0.0
llvmlite==0.35.0
locket==0.2.1
loguru==0.6.0
loompy==3.0.6
lpips==0.1.4
lxml==4.6.2
lzstring==1.0.4
MACS2==2.2.7.1
MACS3==3.0.0a6
Mako==1.1.4
mapclassify==2.4.2
Markdown==3.2.2
markdown-it-py==3.0.0
MarkupSafe==2.1.3
marshmallow==3.15.0
marshmallow-jsonapi==0.24.0
marshmallow-sqlalchemy==0.28.0
matplotlib==3.4.2
mccabe==0.6.1
mdurl==0.1.2
mediapy==1.1.0
megaqc==0.2.0
mercantile==1.2.1
mercurial==6.6.1
meshzoo==0.11.1
methtuple==1.8.0
mgwr==2.1.2
mistune==0.8.4
mmcls==0.25.0
mmcv==1.6.2
mmcv-full==1.5.0
mmengine==0.8.4
mmsegmentation==0.27.0
mock==4.0.2
# Editable install with no version control (molSimplify==1.7.1)
-e /cluster/apps/nss/gcc-6.3.0/molsimplify/1.7.1/x86_64
more-itertools==8.5.0
mpi4py==3.1.3
mpmath==1.1.0
msgpack==1.0.2
msgpack-python==0.5.6
multidict==5.1.0
multiprocess==0.70.11.1
multiqc==1.11
munch==2.5.0
mypy-extensions==1.0.0
natsort==7.0.1
nbclassic==0.2.7
nbclient==0.5.0
nbconvert==6.0.7
nbformat==5.0.7
nbsphinx==0.8.2
nerfacc==0.3.5
nest-asyncio==1.4.1
netCDF4==1.5.6
networkx==2.2
nibabel==3.1.1
ninja==1.10.2.3
nipy==0.5.0
nodeenv==1.7.0
nose==1.3.7
nose-timer==1.0.1
notebook==6.1.4
npTDMS==1.3.1
ntplib==0.4.0
num2words==0.5.10
numba==0.52.0
numexpr==2.7.1
numpy==1.18.5
numpy-groupies==0.9.14
numpydoc==1.1.0
nvdiffrast @ file:///cluster/home/yueshi/code/Tri-MipRF/nvdiffrast
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-ml-py3==7.352.0
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
oauthlib==3.1.0
omegaconf==2.2.3
open3d @ file:///scratch/178766143.tmpdir/Open3D/build/lib/python_package/pip_package/open3d-0.9.0.0-cp38-cp38-linux_x86_64.whl
openbabel==2.4.1
opencensus==0.7.12
opencensus-context==0.1.2
opencv-contrib-python==4.5.1.48
opencv-python==4.6.0.66
OpenEXR==1.3.2
OpenMM==7.7.0
openpyxl==3.0.7
openseespy==3.3.0.0
openseespylinux==3.3.0.0
opt-einsum==3.3.0
ordered-set==4.0.2
ortools==8.0.8283
osqp==0.6.2.post0
outlier-utils==0.0.3
overpy==0.6
packaging==23.1
pamela==1.1.0
pandarallel==1.6.3
pandas==1.5.0
pandas-datareader==0.9.0
pandoc==1.0.2
pandocfilters==1.4.2
parso==0.7.1
partd==1.1.0
passlib==1.7.4
pathos==0.2.7
pathtools==0.1.2
patsy==0.5.1
pbr==5.5.0
pert==2019.11
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.2.0
Pint==0.16.1
piper @ https://github.com/databio/pypiper/archive/refs/tags/v0.10.0.tar.gz
pkginfo==1.7.0
platformdirs==3.10.0
plotly==5.7.0
pluggy==0.13.1
ply==3.11
plyfile==0.8.1
Pmw==2.0.1
point-cloud-utils==0.29.6
pointpats==2.2.0
pomegranate==0.13.5
pooch==1.3.0
pox==0.2.9
ppft==1.6.6.3
pre-commit==2.20.0
prettytable==3.9.0
prometheus-client==0.8.0
promise==2.3
prompt-toolkit==3.0.7
protobuf==3.20.0
psutil==5.7.0
psycopg2-binary==2.9.3
ptyprocess==0.6.0
PuLP==2.3
py==1.10.0
py-machineid==0.4.3
py-spy==0.3.4
py2bit==0.3.0
py4design-cea==0.30
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyBigWig==0.3.18
pybind11==2.7.1
PyBIS==1.35.2
pybktree==1.1
pybufrkit==0.2.18
pycodestyle==2.7.0
pycollada==0.7.1
pycolmap==0.6.1
pycompss @ file:///cluster/scratch/sfux/pycompss-3.1
pycparser==2.20
pydeepimagej==1.1.0
pyDeprecate==0.3.0
pyepsg==0.4.0
pyface==7.3.0
pyfaidx==0.5.9.5
pygame==2.0.1
pygeos==0.9
pyglet==1.4.0b1
Pygments==2.15.1
pygraphviz==1.7
PyGSP==0.5.1
pyGSTi==0.9.9.3
pyhocon==0.3.60
pylint==2.8.2
pymc3==3.11.2
PyMCubes==0.1.2
pymeshfix==0.16.3
pymol==2.5.0
pymongo==3.11.0
PyNaCl==1.5.0
pyngrok==7.1.6
Pyomo==5.7.3
pyopencl==2021.1.6
PyOpenGL==3.1.5
pyOpenSSL==21.0.0
pyparsing==2.4.7
pyproj==3.0.1
pypsa==0.17.1
PyQt5==5.11.3
PyQt5_sip==4.19.19
pyransac3d==0.6.0
pyre-extensions==0.0.29
pyrender==0.1.30
Pyro4==4.80
pyrouge @ git+https://github.com/pltrdy/pyrouge@dfdff03cff1b69bfb18d42dadfb79c79f1caaa18
pyrsistent==0.17.3
pysal==2.4.0
pysam==0.16.0.1
pysdf==0.1.9
pyshp==2.1.3
PySocks==1.7.1
pyspng==0.1.0
pytest==6.2.3
pytest-cov==2.11.1
python-dateutil==2.9.0.post0
python-engineio==4.1.0
python-json-logger==2.0.7
python-license-manager==0.2.8
python-louvain==0.14
python-socketio==5.2.1
pytoml==0.1.21
pytools==2021.2.6
pytz==2020.1
pytz-deprecation-shim==0.1.0.post0
PyUtilib==6.0.0
pyutillib==0.3.0
pyvista==0.39.1
PyWavelets==1.1.1
pyxlsb==1.0.8
PyYAML==6.0
pyzmq==19.0.2
qdldl==0.1.5.post0
qtconsole==4.7.7
QtPy==1.9.0
quantecon==0.5.0
quast==5.0.2
querystring-parser==1.2.4
rasterio==1.2.3
rasterstats==0.15.0
ratelimiter==1.2.0.post0
ray==1.1.0
rdflib==5.0.0
readme-renderer==29.0
recfast4py==0.2.3
recommonmark==0.7.1
redis==3.5.3
rednose==1.3.0
regex==2022.7.9
reportlab==3.5.67
reportseff==2.7.3
requests==2.31.0
requests-cache==1.1.0
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
resampy==0.2.2
retrying==1.3.3
rfc3986==1.4.0
rich==12.6.0
rich-argparse==1.2.0
rpy2==3.5.1
rsa==4.6
Rtree==0.9.7
ruamel.yaml==0.17.4
ruamel.yaml.clib==0.2.2
safetensors==0.3.1
SALib==1.3.13
scikit-image==0.18.0
scikit-learn==0.23.2
scipy==1.9.2
scoary==1.6.16
SCons==4.3.0
scooby==0.7.2
scs==2.1.4
seaborn==0.11.1
SecretStorage==3.3.1
segmentation-refinement==0.6
segregation==1.5.0
semver==2.13.0
Send2Trash==1.5.0
sentry-sdk==1.0.0
serpent==1.30.2
Shapely==1.7.1
shortuuid==1.0.1
simpervisor==1.0.0
simplegeneric==0.8.1
simplejson==3.17.2
six==1.15.0
slicer==0.0.7
smmap==3.0.4
smmap2==3.0.1
snakemake==5.26.1
sniffio==1.2.0
snowballstemmer==2.0.0
snuggs==1.4.7
sortedcontainers==2.3.0
SoundFile==0.10.3.post1
soupsieve==2.2.1
spaghetti==1.5.6
spectra==0.0.11
spglib==1.16.3
spglm==1.0.8
Sphinx==3.2.1
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
sphinxcontrib-websupport==1.2.4
spint==1.0.7
splot==1.1.3
spopt==0.1.1
spreg==1.2.2
spvcm==0.3.0
SQLAlchemy==1.4.31
staticmap==0.5.5
statsmodels==0.12.0
subprocess32==3.5.4
svg.path==4.0.2
sympy==1.6.2
tables==3.6.1
tabulate==0.8.9
tasklogger==1.0.0
taxtastic==0.9.2
tblib==1.7.0
tensorboard==2.9.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.7.0
tensorboardX==2.2
tensorflow==2.4.0
tensorflow-addons==0.14.0
tensorflow-datasets==4.4.0
tensorflow-estimator==2.4.0
tensorflow-graphics-gpu==1.0.0
tensorflow-metadata==1.5.0
tensorflow-probability==0.12.0
termcolor==1.1.0
terminado==0.9.1
terminaltables==3.1.0
termstyle==0.1.11
test-tube==0.7.5
testpath==0.4.4
texttable==1.6.4
Theano==1.0.5
Theano-PyMC==1.1.2
threadpoolctl==2.1.0
tifffile==2020.10.1
timezonefinder==5.2.0
tinycudann @ file:///cluster/home/yueshi/code/Tri-MipRF/tiny-cuda-nn/bindings/torch
tobler==0.7.0
tokenizers==0.12.1
toml==0.10.2
tomli==2.0.1
tomli_w==1.0.0
tomlkit==0.7.2
toolz==0.11.1
toposort==1.5
torch==1.7.1+cu110
torch-efficient-distloss==0.1.3
torch-ema==0.3
torch-fidelity==0.3.0
torch-tb-profiler==0.4.1
torchaudio==0.7.2
torchmetrics==0.10.0
torchtyping==0.1.4
torchvision==0.8.2+cu110
tornado==6.1
tqdm==4.64.1
traitlets==5.0.4
traits==6.2.0
traitsui==7.1.1
trame==2.5.0
trame-client==2.7.7
trame-components==2.1.1
trame-deckgl==2.0.2
trame-markdown==2.0.2
trame-matplotlib==2.0.2
trame-plotly==2.1.1
trame-rca==0.3.1
trame-router==2.0.2
trame-server==2.11.0
trame-simput==2.3.1
trame-vega==2.0.3
trame-vtk==2.4.4
trame-vuetify==2.2.4
transformers==4.19.2
trimesh==3.9.1
triton==2.0.0
twine==3.4.1
typeguard==4.2.1
typing-inspect==0.9.0
typing_extensions==4.11.0
tyro==0.3.25
tzdata==2022.1
tzlocal==4.2
ubiquerg==0.6.2
umi-tools==1.1.2
umsgpack==0.1.0
unicycler @ git+https://github.com/rrwick/Unicycler.git@96ffea71e3a78d63ade19d6124946773e65cf129
url-normalize==1.4.3
urllib3==1.26.6
usd-core==22.5.post1
utm==0.7.0
velocyto==0.17.17
virtualenv==20.17.1
vtk==9.2.6
wandb==0.10.27
wcwidth==0.2.5
webargs==8.1.0
webencodings==0.5.1
Werkzeug==2.3.6
widgetsnbextension==3.5.1
wntr==0.3.0
wrapt==1.12.1
wslink==1.10.2
WTForms==3.0.1
x21==0.4.15
xarray==0.17.0
xatlas==0.0.7
xformers==0.0.21.dev564
xlrd==2.0.1
XlsxWriter==1.4.3
xlwt==1.3.0
xmlrunner==1.7.7
xopen==1.2.1
xxhash==2.0.0
yapf==0.40.1
yarl==1.6.3
zict==2.0.0
zipp==3.3.0
zmq==0.0.0
zope.event==4.5.0
zope.interface==5.4.0
